---
- name: Install vim
  become: true
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    state: latest
    name: vim
 
- name: Install curl
  become: true
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    state: latest
    name: curl

- name: Install zsh
  become: true
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    state: latest
    name: zsh

- name: Install OpenVPN
  become: true
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    state: latest
    name: openvpn
